app/contest/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField, HiddenField, BooleanField


class SubmitProblemForm(FlaskForm):
    contest_id = HiddenField("Contest")
    problem_id = HiddenField("Problem")
    language = SelectField("Language")
    source_code = HiddenField("Source code")
    share = BooleanField("Share your code with others")
    submit = SubmitField("Submit")

    def __init__(self, language=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.language.choices = language or []

app/contest/__init__.py
from flask import Blueprint

contest = Blueprint("contest", __name__)

from . import views

app/contest/views.py
from datetime import datetime

from flask import (
    current_app,
    render_template,
    request,
    flash,
    redirect,
    abort,
    url_for,
    g,
)
from flask_login import login_required, current_user
from sqlalchemy import func

from . import contest
from .forms import SubmitProblemForm
from .utlis import contest_check, generate_board
from .. import tasks
from ..models import db, Problem, Contest, ContestSubmission, User, Permission

supported_languages = ["C", "C++", "Java"]


@contest.route("/")
@login_required
def index():
    page = request.args.get("page", 1, type=int)
    per_page = current_app.config.get("FLASKY_FOLLOWERS_PER_PAGE", 20)
    pagination = Contest.query.order_by(Contest.id.desc()).paginate(
        page, per_page=per_page, error_out=False
    )
    return render_template(
        "contest/index.html",
        contests=pagination.items,
        endpoint=".index",
        pagination=pagination,
    )


@contest.route("/submit/", methods=["POST"])
@login_required
def submit():
    form = SubmitProblemForm([(name, name) for name in supported_languages])
    if not form.validate_on_submit():
        abort(403)
    contest_id = form.contest_id.data
    problem_id = form.problem_id.data
    c = Contest.query.get(int(contest_id))
    if datetime.utcnow() < c.start_time:
        flash("Contest has not begin yet.")
        return redirect(
            url_for(".problem", contest_id=contest_id, problem_id=problem_id)
        )
    if datetime.utcnow() > c.end_time:
        flash("Contest is over.")
        return redirect(
            url_for(".problem", contest_id=contest_id, problem_id=problem_id)
        )
    result = c.get_ori_problem(problem_id)
    if result is None:
        abort(404)
    oj_name, real_pid = result
    language = form.language.data
    if not (
        Problem.query.filter_by(oj_name=oj_name, problem_id=real_pid).first()
        or language not in supported_languages
    ):
        abort(404)
    code = form.source_code.data
    if len(code) < 50 or len(code) > 65536:
        flash(
            "Make sure your code length is longer than 50 and not exceed 65536 Bytes."
        )
        return redirect(
            url_for(".problem", contest_id=contest_id, problem_id=problem_id)
        )
    share = form.share.data
    max_seq = (
        db.session.query(func.max(ContestSubmission.seq))
        .filter_by(contest_id=c.id)
        .first()[0]
        or 0
    )
    submission = ContestSubmission(
        user_id=current_user.id,
        seq=max_seq + 1,
        contest_id=contest_id,
        oj_name=oj_name,
        problem_id=real_pid,
        language=language,
        source_code=code,
        share=share,
    )
    db.session.add(submission)
    db.session.commit()
    tasks.submit_problem.delay(submission.id, in_contest=True)
    return redirect(url_for(".status", contest_id=submission.contest_id))


@contest.route("/<contest_id>/problem/<problem_id>")
@contest_check
@login_required
def problem(contest_id, problem_id):
    contest = g.contest
    result = contest.get_ori_problem(problem_id)
    if result is None:
        abort(404)
    oj_name, real_pid = result
    problem = Problem.query.filter_by(oj_name=oj_name, problem_id=real_pid).first()
    if problem is None:
        abort(404)
    form = SubmitProblemForm()
    form.contest_id.data = contest_id
    form.problem_id.data = problem_id
    source_code = ""
    language = "C++"
    if current_user.is_authenticated:
        res = (
            db.session.query(
                ContestSubmission.source_code.label("code"),
                ContestSubmission.language.label("lang"),
            )
            .filter_by(
                user_id=current_user.id,
                contest_id=contest.id,
                oj_name=oj_name,
                problem_id=real_pid,
            )
            .order_by(ContestSubmission.id.desc())
            .first()
        )
        if res:
            source_code = res.code
            language = res.lang

    return render_template(
        "contest/problem.html",
        contest=contest,
        problem=problem,
        form=form,
        source_code=source_code,
        language=language,
    )


@contest.route("/<contest_id>/problem")
@contest_check
@login_required
def problem_list(contest_id):
    page = request.args.get("page", 1, type=int)
    per_page = current_app.config.get("FLASKY_FOLLOWERS_PER_PAGE", 20)
    contest = g.contest
    pagination = (
        Problem.query.filter_by(oj_name=contest.clone_name)
        .order_by(Problem.problem_id)
        .paginate(page, per_page=per_page, error_out=False)
    )
    return render_template(
        "contest/problem_list.html",
        contest=contest,
        problems=pagination.items,
        endpoint=".problem_list",
        pagination=pagination,
    )


@contest.route("/<contest_id>/status")
@contest_check
@login_required
def status(contest_id):
    id = request.args.get("id", None, type=int)
    username = request.args.get("user")
    verdict = request.args.get("verdict", None)
    page = request.args.get("page", None, type=int)
    contest = g.contest

    query_dict = dict(seq=id, username=username, verdict=verdict, page=page)

    query_args = {}
    for k in query_dict:
        if query_dict[k] is not None:
            query_args[k] = query_dict[k]
    query_args["contest_id"] = contest_id

    page = page if page else 1
    if "page" in query_args:
        query_args.pop("page")
    per_page = current_app.config.get("FLASKY_FOLLOWERS_PER_PAGE", 20)

    if "username" in query_args:
        username = query_args.pop("username")
        query_args["user_id"] = (
            db.session.query(User.id.label("user_id"))
            .filter_by(username=username)
            .first()
            .user_id
        )

    pagination = (
        ContestSubmission.query.filter_by(**query_args)
        .order_by(ContestSubmission.id.desc())
        .paginate(page, per_page=per_page, error_out=False)
    )
    submissions = []
    for item in pagination.items:
        u = User.query.get(item.user_id)
        name = u.username if u is not None else ""
        submissions.append({"username": name, "data": item})

    return render_template(
        "contest/status.html",
        contest=contest,
        submissions=submissions,
        endpoint=".status",
        pagination=pagination,
    )


@contest.route("/<contest_id>/ranklist")
@contest_check
@login_required
def rank_list(contest_id):
    contest = g.contest
    board = generate_board()
    return render_template("contest/rank_list.html", contest=contest, board=board)


@contest.route("/<contest_id>/source")
@contest_check
@login_required
def source_code(contest_id):
    contest = g.contest
    seq = request.args.get("id", 0, type=int)
    submission = ContestSubmission.query.filter_by(
        contest_id=contest.id, seq=seq
    ).first()
    if not submission:
        abort(404)

    if (
        not current_user.can(Permission.ADMINISTER)
        and submission.user_id != current_user.id
        and (
            datetime.utcnow() < contest.end_time
            or not current_user.can(Permission.MODERATE)
            and not submission.share
        )
    ):
        abort(403)

    u = User.query.get(submission.user_id)
    username = u.username if u else ""
    language = "c_cpp"
    if submission.language == "Java":
        language = "java"
    return render_template(
        "contest/source_code.html",
        contest=contest,
        submission=submission,
        username=username,
        language=language,
    )

app/templates/contest/base.html
{% extends "base.html" %}

{% block navbar %}
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">Home</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('contest.problem_list', contest_id=contest.id) }}">Problem</a></li>
                </ul>
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('contest.status', contest_id=contest.id) }}">Status</a></li>
                </ul>
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('contest.rank_list', contest_id=contest.id) }}">Ranklist</a></li>
                </ul>
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('contest.index') }}">Contest</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="{{ url_for('static', filename='avatar/small.png') }}">
                                {{ current_user.username }}<b
                                    class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ url_for('main.user', username=current_user.username) }}">Profile</a>
                                </li>
                                <li><a href="{{ url_for('auth.change_password') }}">Change Password</a></li>
                                <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}}

app/templates/contest/index.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}
{% block title %}VJudge - Contest list{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
{% endblock %}

{% block page_content %}
    <div class="page-header">
        <h1>Contest list</h1>
    </div>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>Contest</th>
            <th>Title</th>
            <th>StartTime</th>
            <th>EndTime</th>
            <th>Status</th>
        </tr>
        </thead>
        {% for contest in contests %}
            <tr>
                <td>
                    <a href="{{ url_for('contest.problem_list',contest_id=contest.id) }}">
                        {{ contest.id }}</a>
                </td>
                <td>
                    <a href="{{ url_for('contest.problem_list',contest_id=contest.id) }}">
                        {{ contest.title }}</a>
                </td>
                <td>{{ moment(contest.start_time).format('YYYY-MM-DD HH:mm') }}</td>
                <td>{{ moment(contest.end_time).format('YYYY-MM-DD HH:mm') }}</td>
                <td>{{ contest.status }}</td>
            </tr>
        {% endfor %}
    </table>
    <div class="pagination">
        {{ macros.pagination_widget(pagination, endpoint) }}
    </div>
{% endblock %}

app/templates/contest/problem.html
{% extends "contest/base.html" %}
{% block title %}VJudge - {{ contest.title }}-{{ problem.problem_id }}{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>{% autoescape false %}{{ problem.title }}{% endautoescape %}</h1>
</div>
<div class="row">
    <div class=" col-md-9 col-sm-12 col-xs-12">
        <div class="panel panel-default">
            <div class="panel-heading"><b>Description</b></div>
            <div class="panel-body">
                {% autoescape false %}
                {{ problem.description }}
                {% endautoescape %}
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading"><b>Input</b></div>
            <div class="panel-body">
                {% autoescape false %}
                {{ problem.input }}
                {% endautoescape %}
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading"><b>Output</b></div>
            <div class="panel-body">
                {% autoescape false %}
                {{ problem.output }}
                {% endautoescape %}
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading"><b>Sample input</b></div>
            <div class="panel-body">
                {% autoescape false %}
                {{ problem.sample_input }}
                {% endautoescape %}
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading"><b>Sample output</b></div>
            <div class="panel-body">
                {% autoescape false %}
                {{ problem.sample_output }}
                {% endautoescape %}
            </div>
        </div>
        <form id="submit_form" method="post" action="{{ url_for('contest.submit') }}" onsubmit="submitEncode()">
            {{ form.hidden_tag() }}
            <div class="row">
                <div class="col-md-6 col-sm-6 col-xs-6 problem-limit">
                    <b>Time limit:&nbsp;</b>
                    {% if problem.time_limit %}
                        {{ problem.time_limit }}
                    {% else %} 1000 {% endif %}
                    &nbsp;ms<br>
                    <b>Memory limit:&nbsp;</b>
                    {% if problem.mem_limit %}
                        {{ problem.mem_limit }}
                    {% else %} 65536 {% endif %}
                    &nbsp;kb
                </div>
                <div class="col-md-6 col-sm-6 col-xs-6">
                    <div class="form-group pull-right">
                        <label>
                            <select id="{{ language }}" class="selectpicker form-control" name="language"
                                    data-live-search="true"
                                    data-width="100px">
                                <option value="C" data-tokens="C">C</option>
                                <option value="C++" data-tokens="C++" selected>C++</option>
                                <option value="Java" data-tokens="Java">Java</option>
                            </select>
                        </label>
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div id="editor">{{ source_code }}</div>
            </div>
            <div class="problem-submit checkbox">
                <button type="submit" class="btn btn-primary">Submit</button>
                <label>
                    <input id="share" name="share" type="checkbox" value="y">
                    <span>Share your code with others</span>
                </label>
            </div>

        </form>
    </div>
</div>
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script type="text/x-mathjax-config">
    MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}});
    </script>
    <script type="text/javascript" async
            src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML">
    </script>
    <script src="https://cdn.bootcss.com/ace/1.2.9/ace.js"></script>
    <script src="https://cdn.bootcss.com/ace/1.2.9/ext-language_tools.js"></script>
    <script src="https://cdn.bootcss.com/ace/1.2.9/theme-chrome.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>
    <script>
        let editor = ace.edit("editor");
        editor.session.setMode("ace/mode/c_cpp");
        editor.setTheme("ace/theme/chrome");
        editor.setAutoScrollEditorIntoView(true);
        document.getElementById('editor').style.fontSize = '14px';
        $(document).ready(function () {
            s = $("select");
            s.val(s.attr('id'));
            switch (s.val()) {
                case "C":
                    editor.session.setMode("ace/mode/c_cpp");
                    break;
                case "C++":
                    editor.session.setMode("ace/mode/c_cpp");
                    break;
                case  "Java":
                    editor.session.setMode("ace/mode/java");
                    break;
            }
            $s.change(function () {
                switch ($(this).val()) {
                    case "C":
                        editor.session.setMode("ace/mode/c_cpp");
                        break;
                    case "C++":
                        editor.session.setMode("ace/mode/c_cpp");
                        break;
                    case  "Java":
                        editor.session.setMode("ace/mode/java");
                        break;
                }
            });
        });

        function submitEncode() {
            let form = document.getElementById('submit_form');
            form.source_code.value = editor.getValue();
        }
    </script>
{% endblock %}

app/templates/contest/problem_list.html
{% extends "contest/base.html" %}
{% import "_macros.html" as macros %}
{% block title %}VJudge - Problem list{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>{{ contest.title }}</h1>
</div>
<table class="table table-hover">
    <thead>
    <tr>
        <th>Problem</th>
        <th>Name</th>
        <th>Last update</th>
    </tr>
    </thead>
    {% for problem in problems %}
    <tr>
        <td>
            <a href="{{ url_for('.problem',contest_id=contest.id,problem_id=problem.problem_id) }}">
                {{ problem.problem_id }}</a>
        </td>
        <td>
            <a href="{{ url_for('.problem',contest_id=contest.id,problem_id=problem.problem_id) }}">
                {% autoescape false %}{{ problem.title }}{% endautoescape %}</a>&nbsp;
            {% if current_user.can(Permission.MODERATE) %}
                <button type="button" class="btn btn-default">
            <span class="glyphicon glyphicon-refresh problem-refresh"
                  id="{{ problem.oj_name }}-{{ problem.problem_id }}"></span>
                </button>
            {% endif %}
        </td>
        <td>{{ moment(problem.last_update).format('YYYY-MM-DD HH:mm') }}</td>
    </tr>
    {% endfor %}
</table>
<div class="pagination">
    {{ macros.pagination_widget(pagination, endpoint, contest_id=contest.id) }}
</div>
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>
    <script>
        $(document).ready(function () {
            $(".problem-refresh").click(function () {
                var prob = $(this).attr('id').split('-');
                var url = 'refresh-problem/' + prob[0] + '/' + prob[1];
                $.post(url);
            });
            s = $("select");
            s.val(s.attr('id'));
        });
    </script>
{% endblock %}

app/templates/contest/rank_list.html
{% extends "contest/base.html" %}
{% import "_macros.html" as macros %}
{% block title %}VJudge - {{ contest.title }} - Ranklist{% endblock %}

{% block page_content %}
    <div class="page-header">
        <h1>Ranklist</h1>
    </div>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>User</th>
            <th>Solved</th>
            <th>Penalty</th>

            {% for pid in contest.get_ori_problems() %}
                <th><a href="{{ url_for('.problem',contest_id=contest.id,problem_id=pid) }}">
                    {{ pid }}</a>&nbsp;
                </th>
            {% endfor %}
        </tr>
        </thead>
        {% for record in board %}
            <tr>
                <td><a href="{{ url_for('main.user', username = record.username) }}">
                    <img class="img-rounded" src="{{ url_for('static', filename='avatar/middle.png') }}">
                    {{ record.username }}
                </a></td>
                <td>{{ record.solved }}</td>
                <td>{{ record.penalty }}</td>
                {% for item in record.problem %}
                    <td>{% if item[1] %}{{ item[1] }}{% endif %}
                        {% if item[1] and item[2] %}<br>{% endif %}
                        {% if item[2] %}-{{ item[2] }}{% endif %}</td>
                {% endfor %}
            </tr>
        {% endfor %}
    </table>
{% endblock %}

app/templates/contest/source_code.html
{% extends "contest/base.html" %}
{% block title %}VJudge - Source code{% endblock %}
{% block page_content %}
    <div class="col-md-8 col-sm-12 col-xs-12">
        <div class="page-header">
            <h1>{{ username }}'s solution for problem
                [<a href="{{ url_for('contest.problem', contest_id=contest.id, problem_id=submission.problem_id) }}">{{ submission.problem_id }}</a>]
            </h1>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading"></div>
            <div id="editor">{{ submission.source_code }}</div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="https://cdn.bootcss.com/ace/1.2.9/ace.js"></script>
    <script src="https://cdn.bootcss.com/ace/1.2.9/ext-language_tools.js"></script>
    <script src="https://cdn.bootcss.com/ace/1.2.9/theme-chrome.js"></script>
    <script>
        var editor = ace.edit("editor");
        editor.session.setMode("ace/mode/{{ language }}");
        editor.setTheme("ace/theme/chrome");
        editor.setReadOnly(true);
        editor.setAutoScrollEditorIntoView(true);

        document.getElementById('editor').style.fontSize = '14px';
        $(document).ready(function () {
            var heightUpdateFunction = function () {
                var newHeight =
                    editor.getSession().getScreenLength()
                    * editor.renderer.lineHeight
                    + editor.renderer.scrollBar.getWidth();
                $('#editor').height(newHeight.toString() + "px");
                editor.resize();
            };
            heightUpdateFunction();
            editor.getSession().on('change', heightUpdateFunction);
        });
    </script>
{% endblock %}

app/templates/contest/status.html
{% extends "contest/base.html" %}
{% import "_macros.html" as macros %}
{% block title %}VJudge - Status{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
{% endblock %}

{% block page_content %}
    <div class="page-header">
        <h1>Status</h1>
    </div>

    <table class="table table-hover">
        <thead>
        <tr>
            <th>ID</th>
            <th>User</th>
            <th>Problem</th>
            <th>Lang</th>
            <th>Verdict</th>
            <th>Time</th>
            <th>Memory</th>
            <th>Submit time</th>
        </tr>
        </thead>
        {% for submission in submissions %}
            <tr class="align-middle align-text-top">
                <td>{{ submission.data.seq }}</td>
                <td><a href="{{ url_for('main.user', username = submission.username) }}">
                    <img class="img-rounded" src="{{ url_for('static', filename='avatar/middle.png') }}">
                    {{ submission.username }}
                </a></td>
                <td>
                    <a href="{{ url_for('contest.problem',contest_id=submission.data.contest_id,problem_id=submission.data.problem_id) }}">{{ submission.data.problem_id }}</a>
                </td>
                <td>
                    {% if current_user.is_authenticated and (submission.data.share or current_user.id == submission.data.user_id
            or current_user.can(Permission.MODERATE)) %}
                        <a href="{{ url_for('contest.source_code',contest_id=submission.data.contest_id, id=submission.data.seq ) }}">{{ submission.data.language }}</a>
                    {% else %}
                        {{ submission.data.language }}
                    {% endif %}
                </td>
                <td class="{{ submission.data.verdict.replace(' ','-').lower() }} verdict">{{ submission.data.verdict }}</td>
                <td>{{ submission.data.exe_time }}</td>
                <td>{{ submission.data.exe_mem }}</td>
                <td>{{ moment(submission.data.time_stamp).format('YYYY-MM-DD HH:mm:ss') }}</td>
            </tr>
        {% endfor %}
    </table>
    <div class="pagination">
        {{ macros.pagination_widget(pagination, endpoint,contest_id=contest.id) }}
    </div>
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>
{% endblock %}